name: Delete Old Workflows
on:
  # schedule:
  #   - cron: "0 2 * * 0"
  workflow_dispatch:
      created_before:
        description: Created before (YYYY-MM-DD)
        default: "2022-01-01"
        required: true
jobs:
  # This workflow contains a single job called "delete_old"
  delete_old:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: joschkappel/dunkomatic_next
          created-before: "${{ github.event.inputs.created_before }}T00:00:00Z"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
