name: Laravel Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runner-job:

    runs-on: ubuntu-latest

    steps:
    - name: get sourcees
      uses: actions/checkout@v3
    - name: Setup PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
    - name: Copy ENV Laravel Configuration for CI
      run: |
        cp .env.dusk.git .env
        chmod -R 777 storage bootstrap/cache
        mkdir -m 777 -p storage/app/exports/2020_21/HBVDA/vereine
        mkdir -m 777 -p storage/app/exports/2020_21/HBVDA/runden
        mkdir -m 777 -p storage/app/backup
    - name: install dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist -o
        rm -rf package-lock.json
        npm i -D --no-scripts && npm run prod
    - name: Create Database
      run: |
        sudo systemctl start mysql
        mysql --user="root" --password="root" -e "CREATE DATABASE dunkomatic_test character set UTF8mb4 collate utf8mb4_bin;"
        mysql --user="root" --password="root" -e  "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"
    - name: Create Schema
      run: php artisan migrate
    - name: app key
      run: php artisan key:generate
    - name: Seed static tables
      run: php artisan db:seed --class=TestDatabaseSeeder
    - name: Run phpunit tests
      run: php artisan test --stop-on-defect --stop-on-error
    - name: Archive laravel logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: laravel_logs
        path: storage/logs/
