name: PHP Composer

on:
  push:
    branches: [ master, laravel8 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy ENV Laravel Configuration for CI
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Dependencies (PHP vendors)
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Install NPM Dependencies
      run: npm install
    - name: Generate key
      run: php artisan key:generate      
    - name: Create DB and schemas
      run: |
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate
    - name: Seed static tables
      run: php artisan db:seed --class TestDatabaseSeeder
    - name: run phpunit tests
      run: php artisan test
    - name: Prepare Dusk Environment
      run: cp .env.dusk.local .env
    - name: Create Database
      run: |
        sudo systemctl start mysql
        mysql --user="root" --password="root" -e "CREATE DATABASE 'dunkomatic_next' character set UTF8mb4 collate utf8mb4_bin;"
    - name: Upgrade Chrome Driver
      run: php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`
    - name: Start Chrome Driver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux &
    - name: Run Laravel Server
      run: php artisan serve &
    - name: Run Dusk Tests
      env:
        APP_URL: "http://127.0.0.1:8000"
      run: php artisan dusk
        
